version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
      parallelism: 4
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Dependencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: Run Test and Coverage
          command: |
            npm test -- --coverage
      - run: # run coveralls
          name: Send to coveralls
          command: |
            COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
       
